### ISSUE TITLE
does not work on dark background

### ISSUE THREAD

**Issue by seabadger** [splondike/talon_telector#1]
I'm using dark mode, and I don't think telector is able to detect the text area.

**Comment by seabadger** [comment]
hmmm. maybe not -- in some cases it works fine. Maybe mouse was not over background properly. I'll reopen if I can get a better idea of what happens.

**Comment by splondike** [comment]
For the automatic detector, the colour of the background and forground shouldn't matter, as long as:

* There's only one background colour (i.e. it won't handle selected text correctly).
* There's a distinct border for the text area.
* You hover a background pixel with the mouse.

**Comment by splondike** [comment]
It's also possible you ran in to the [Talon active window rectangle bug on Linux](https://github.com/talonvoice/talon/issues/285). There's a setting to work around that using xdotool called 'user.telector_enable_win_rect_workaround'.
